[package]
name = "cryo-sessions"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
redis = { version = "0.23.3", features = ["r2d2", "ahash", "tokio-comp"] }
